name: Release

# Runs when a new tag is created.  Creates a release for that tag, then builds
# ffmpeg and ffprobe on all OS & CPU combinations, then attaches them to the
# release.
on:
  push:
    tags:
      - "*"

env:
  FFMPEG_TAG: "n4.4"
  LIBVPX_TAG: "v1.9.0"
  AOM_TAG: "v3.1.2"
  X264_TAG: "stable"
  X265_TAG: "stable"
  LAME_VERSION: "3.100"
  OPUS_VERSION: "1.3.1"
  VORBIS_VERSION: "1.3.7"

defaults:
  run:
    shell: bash

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.draft_release.outputs.release_id }}
    steps:
      - name: Checkout repo
        run: git clone --depth 1 https://github.com/"$GITHUB_REPOSITORY" repo-src

      - name: Draft release
        id: draft_release
        uses: ./repo-src/.github/workflows/custom-github-repo-api-action
        with:
          username: shaka-bot
          token: ${{ secrets.SHAKA_BOT_TOKEN }}
          method: 'draft_release("${{ github.ref }}")'

  build:
    needs: draft_release
    strategy:
      matrix:
        # TODO: Add Mac arm64?
        # TODO: Add Windows arm64?
        os: ["ubuntu-latest", "macos-latest", "windows-latest", "linux-arm64"]
        include:
          - os: ubuntu-latest
            os_name: linux
            target_arch: x64
            exe_ext: ""
          - os: macos-latest
            os_name: osx
            target_arch: x64
            exe_ext: ""
          - os: windows-latest
            os_name: win
            target_arch: x64
            exe_ext: ".exe"
          - os: linux-arm64
            os_name: linux
            target_arch: arm64
            exe_ext: ""

    name: Build ${{ matrix.os_name }} ${{ matrix.target_arch }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          set -e
          set -x
          sudo apt -y install \
            cmake \
            mercurial \
            nasm \
            pkg-config \
            yasm \
            libffmpeg-nvenc-dev \
            libvdpau-dev
          # Use sudo in install commands on Linux.
          echo "SUDO=sudo" >> "$GITHUB_ENV"

      - name: Install macOS packages
        if: runner.os == 'macOS'
        run: |
          set -e
          set -x
          brew install \
            md5sha1sum \
            mercurial \
            nasm \
            yasm
          # Unlink homebrew packages that conflict with our static library
          # builds below.
          brew unlink \
            lame \
            opus \
            opusfile \
            xz
          # Use sudo in install commands on macOS.
          echo "SUDO=sudo" >> "$GITHUB_ENV"

      - name: Add msys2 to the Windows path
        if: runner.os == 'Windows'
        run: |
          # At this point, we're running Git Bash.  After this step, we will be
          # running msys bash, just as we would be in tmate.
          echo "C:\\msys64\\usr\\bin" >> "$GITHUB_PATH"
          echo "C:\\msys64\\mingw64\\bin" >> "$GITHUB_PATH"

      - name: Install Windows packages
        if: runner.os == 'Windows'
        run: |
          set -e
          set -x
          pacman -Sy --noconfirm \
            git \
            mercurial \
            nasm \
            yasm
          # Make sure that cmake builds makefiles and not ninja files.
          echo "CMAKE_GENERATOR=MSYS Makefiles" >> "$GITHUB_ENV"
          # Make sure that pkg-config searches the expected path.
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" >> "$GITHUB_ENV"

      - name: Debug cert issues in python
        shell: python3 {0}
        run: |
          import urllib.request
          import sys
          print("[DEBUG] Python executable", sys.executable)
          try:
            urllib.request.urlopen("https://api.github.com/repos/joeyparrish/static-ffmpeg-binaries/releases")
            print("[DEBUG] urllib request OK")
          except Exception as e:
            print("[DEBUG] urllib request failed", e)

      - name: Debug cert issues in nodejs, part 1
        run: |
          $SUDO npm install -g @octokit/rest

      - name: Debug cert issues in nodejs, part 2
        shell: node {0}
        run: |
          const { Octokit } = require('@octokit/rest');
          const octokit = new Octokit();
          (async () => {
            const { data } = await octokit.rest.repos.listReleases({
              owner: 'joeyparrish',
              repo: 'static-ffmpeg-binaries',
            });
            console.log(data);
          })();

      - name: Install libvpx
        run: |
          set -e
          set -x
          git clone --depth 1 https://chromium.googlesource.com/webm/libvpx -b "$LIBVPX_TAG"
          cd libvpx
          # NOTE: disabling unit tests and examples significantly reduces build
          # time (by 80% as tested on a Jetson Nano)
          ./configure \
            --enable-vp8 \
            --enable-vp9 \
            --enable-runtime-cpu-detect \
            --disable-unit-tests \
            --disable-examples \
            --enable-static \
            --disable-shared
          make
          $SUDO make install

      - name: Install aom
        run: |
          set -e
          set -x
          git clone --depth 1 https://aomedia.googlesource.com/aom/ -b "$AOM_TAG"
          mkdir aom_build
          cd aom_build
          # NOTE: without CMAKE_INSTALL_PREFIX on Windows, files are installed
          # to c:\Program Files.
          cmake ../aom \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DENABLE_DOCS=OFF \
            -DENABLE_EXAMPLES=OFF \
            -DENABLE_TESTS=OFF \
            -DENABLE_TESTDATA=OFF \
            -DENABLE_TOOLS=OFF \
            -DCONFIG_RUNTIME_CPU_DETECT=1 \
            -DCONFIG_SHARED=0
          make
          $SUDO make install
          # This adjustment to the aom linker flags is needed, at least on
          # arm, to successfully link against it statically.  (-lm missing)
          $SUDO sed -e 's/-laom/-laom -lm/' -i.bk /usr/local/lib/pkgconfig/aom.pc

      - name: Install x264
        run: |
          set -e
          set -x
          git clone --depth 1 https://code.videolan.org/videolan/x264.git -b "$X264_TAG"
          cd x264
          ./configure \
            --enable-static
          make libx264.a
          $SUDO make install-lib-static

      - name: Install x265
        run: |
          set -e
          set -x
          hg clone http://hg.videolan.org/x265 -r "$X265_TAG"
          cd x265/build
          # NOTE: without CMAKE_INSTALL_PREFIX on Windows, files are installed
          # to c:\Program Files.
          cmake ../source \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DENABLE_SHARED=OFF \
            -DENABLE_CLI=OFF
          make
          $SUDO make install
          # This adjustment to the x265 linker flags is needed, at least on
          # arm, to successfully link against it statically.  (-lgcc_s not
          # found (or needed), and -lpthread missing)
          $SUDO sed -e 's/-lgcc_s -lgcc -lgcc_s -lgcc/-lpthread -lgcc/' -i.bk /usr/local/lib/pkgconfig/x265.pc

      - name: Install lame
        run: |
          set -e
          set -x
          curl -L -o lame-"$LAME_VERSION".tar.gz https://sourceforge.net/projects/lame/files/lame/"$LAME_VERSION"/lame-"$LAME_VERSION".tar.gz/download
          tar xzf lame-"$LAME_VERSION".tar.gz
          cd lame-"$LAME_VERSION"
          # Only build and install the library (--disable-front-end).  The
          # frontend doesn't build on Windows, and we don't need it anyway.
          # On Windows, somehow prefix defaults to / instead of /usr/local, but
          # only on some projects.  No idea why.
          ./configure \
            --prefix=/usr/local \
            --disable-frontend \
            --enable-static \
            --disable-shared
          make
          $SUDO make install

      - name: Install opus
        run: |
          set -e
          set -x
          curl -LO https://archive.mozilla.org/pub/opus/opus-"$OPUS_VERSION".tar.gz
          tar xzf opus-"$OPUS_VERSION".tar.gz
          cd opus-"$OPUS_VERSION"
          # On Windows, we can't link later if we build with -D_FORTIFY_SOURCE
          # now.  But there is no configure option for this, so we edit the
          # configure script instead.
          sed -e 's/-D_FORTIFY_SOURCE=2//' -i.bk configure
          # On Windows, somehow prefix defaults to / instead of /usr/local, but
          # only on some projects.  No idea why.
          # On Windows, we also need to disable-stack-protector.
          ./configure \
            --prefix=/usr/local \
            --disable-extra-programs \
            --disable-stack-protector \
            --enable-static \
            --disable-shared
          make
          $SUDO make install
          # The pkgconfig linker flags for static opus don't work when ffmpeg
          # checks for opus in configure.  Linking libm after libopus fixes it.
          $SUDO sed -e 's/-lopus/-lopus -lm/' -i.bk /usr/local/lib/pkgconfig/opus.pc

      - name: Build ffmpeg and ffprobe
        run: |
          set -e
          set -x
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git -b "$FFMPEG_TAG"
          cd ffmpeg
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            export CFLAGS="-static"
            export LDFLAGS="-static"

            # Enable platform-specific hardware acceleration.
            PLATFORM_CONFIGURE_FLAGS="--enable-nvenc --enable-vdpau"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            export CFLAGS="-static"
            # You can't do a _truly_ static build on macOS except the kernel.
            # So don't set LDFLAGS.  See https://stackoverflow.com/a/3801032

            # Enable platform-specific hardware acceleration.
            PLATFORM_CONFIGURE_FLAGS="--enable-videotoolbox"

            # Disable x86 ASM on macOS.  It fails to build with an error about
            # how macho64 format can't contain 32-bit assembly.  I'm not sure
            # how else to resolve this, and from my searches, it appears that
            # others are not having this problem with ffmpeg.
            # TODO: Try building from master branch to see if this has been
            # resolved more recently than n4.4.
            PLATFORM_CONFIGURE_FLAGS="$PLATFORM_CONFIGURE_FLAGS --disable-x86asm --disable-inline-asm"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            export CFLAGS="-static"
            # Surprisingly, /usr/local/lib is not in the mingw linker path by
            # default.
            export LDFLAGS="-static -L/usr/local/lib"

            # Convince ffmpeg that we want to build for mingw64 (native
            # Windows), not msys.  Since we're in an msys environment, ffmpeg
            # reasonably assumes we're building for that environment if we
            # don't specify this.
            PLATFORM_CONFIGURE_FLAGS="--target-os=mingw64"
          fi
          ./configure \
            --pkg-config-flags="--static" \
            --disable-ffplay \
            --enable-libvpx \
            --enable-libaom \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-runtime-cpudetect \
            --enable-gpl \
            --enable-version3 \
            --enable-static \
            $PLATFORM_CONFIGURE_FLAGS
          make

      - name: Check that executables are static
        run: |
          set -e
          set -x
          cd ffmpeg
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            # If ldd succeeds, then these are dynamic executables, so we fail
            # this step if ldd succeeds.
            ldd ffmpeg && exit 1
            ldd ffprobe && exit 1
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            # These will still be dynamic executables, but they should not link
            # against anything outside of /c/Windows.  The grep command will
            # succeed if it can find anything outside /c/Windows, and then we
            # fail if that succeeds.
            ldd ffmpeg.exe | grep -qvi /c/Windows/ && exit 1
            ldd ffprobe.exe | grep -qvi /c/Windows/ && exit 1
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            # These will still be dynamic executables, but they should not link
            # against anything outside of /usr/lib or /System/Library.  The
            # grep command will succeed if it can find anything outside
            # these two folders, and then we fail if that succeeds.
            otool -L ffmpeg | grep '\t' | grep -Evq '(/System/Library|/usr/lib)' && exit 1
            otool -L ffprobe | grep '\t' | grep -Evq '(/System/Library|/usr/lib)' && exit 1
          fi
          # After commands that we expect to fail, we still need a successful
          # command here to make this step a success.
          true

      - name: Prepare assets
        run: |
          set -e
          set -x
          mkdir assets
          SUFFIX="-${{ matrix.os_name }}-${{ matrix.target_arch }}${{ matrix.exe_ext}}"
          cp ffmpeg/ffmpeg assets/ffmpeg"$SUFFIX"
          cp ffmpeg/ffprobe assets/ffprobe"$SUFFIX"
          # Show sizes and MD5 sums that can be verified by users later if they
          # want to check for authenticity.
          cd assets
          wc -c *
          md5sum *

      - name: Checkout repo
        run: git clone --depth 1 https://github.com/"$GITHUB_REPOSITORY" repo-src

      - name: Attach assets to release
        uses: ./repo-src/.github/workflows/custom-github-repo-api-action
        with:
          username: shaka-bot
          token: ${{ secrets.SHAKA_BOT_TOKEN }}
          method: 'upload_all_assets("${{ needs.draft_release.outputs.release_id }}", "assets/")'

      # TODO: unfork with arm64 PR lands
      # TODO: remove once we fix CA certs on Windows
      - name: Debug
        uses: joeyparrish/action-tmate@v5
        with:
          limit-access-to-actor: true
        if: failure()

  publish_release:
    name: Publish release
    needs: [draft_release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        run: git clone --depth 1 https://github.com/"$GITHUB_REPOSITORY" repo-src

      # First, we have to take the release out of draft mode.  Then, we can
      # download the assets and use their MD5 sums to update the release notes.
      - name: Publish release
        uses: ./repo-src/.github/workflows/custom-github-repo-api-action
        with:
          username: shaka-bot
          token: ${{ secrets.SHAKA_BOT_TOKEN }}
          method: 'update_release("${{ needs.draft_release.outputs.release_id }}", draft=False)'

      - name: Get all release assets
        uses: ./repo-src/.github/workflows/custom-github-repo-api-action
        with:
          username: shaka-bot
          token: ${{ secrets.SHAKA_BOT_TOKEN }}
          method: 'download_all_assets("${{ needs.draft_release.outputs.release_id }}", "assets/")'

      - name: Calculate MD5 sums of all release assets
        id: md5sum
        run: |
          set -e
          set -x
          cd assets
          SUMS=$(md5sum *)
          echo "::set-output name=sums::$SUMS"
          # The sums are now in an output variable that we can use in the next
          # step to set the release body.

      - name: Update release notes
        uses: ./repo-src/.github/workflows/custom-github-repo-api-action
        with:
          username: shaka-bot
          token: ${{ secrets.SHAKA_BOT_TOKEN }}
          method: 'update_release("${{ needs.draft_release.outputs.release_id }}", body="MD5 sums:\n${{ steps.md5sum.outputs.sums }}")'
